; ESP32 Asteroids — PlatformIO Configuration
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

; Libraries
lib_deps =
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.5

; Tell IntelliSense about our include/ directory
build_flags = -I include

; Faster flash
board_build.flash_mode = dio
board_build.f_flash = 80000000L