[platformio]
default_envs = pir_board, camera_board

[env:pir_board]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_src_filter = +<PIR_Node/pir_board.cpp>
lib_deps = blynkkk/Blynk@^1.3.2

[env:camera_board]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, direct, time

# Only compile the camera folder
build_src_filter = +<Camera_Node/camera_board.cpp>

board_build.flash_mode = qio ; Try qio first, switch to dout only if it fails to boot
board_build.f_flash = 80000000L

# CRITICAL FOR MJPEG AND MUGSHOTS
build_flags = 
    -DBOARD_HAS_PSRAM 
    -mfix-esp32-psram-cache-issue
lib_deps = 
    blynkkk/Blynk@^1.3.2